### PR TITLE
feat: Create a new Quiz prompt

### PR DESCRIPTION
**Pull request by rajat-sr**

### CODE REVIEW

**Comment by rajat-sr** [comment]
Example Quiz Prompt
enquirer-quiz

**Comment by doowb** [comment]
@rajat-sr thanks for the PR!

We've been working on updating and fixing issues in the examples that I forgot to mention this for new prompts... Will you also update the [prompt docs](https://github.com/enquirer/enquirer/blob/master/docs/prompts.md) to include information on this prompt?

You don't need to rebuild the README, just update the docs. Thanks!

**Comment by rajat-sr** [comment]
Sure, I'll update all the docs.

**Comment by doowb** [comment]
Thanks for the docs! I'll merge both of these in.

**Pull request merged**
