### PR TITLE
Fix: prompt in child_process

### PR DESCRIPTION
**Pull request by whxaxes**
Hi, enquirer is awesome but when I use it in child_process, it throw this error

```
(node:81812) UnhandledPromiseRejectionWarning: Error: Invalid stream passed
    at Function.keypress.listen (/Users/wanghx/Workspace/larva-team/common-bin-plus/node_modules/enquirer/lib/keypress.js:191:11)
    at Input.start (/Users/wanghx/Workspace/larva-team/common-bin-plus/node_modules/enquirer/lib/prompt.js:169:28)
    at Input.initialize (/Users/wanghx/Workspace/larva-team/common-bin-plus/node_modules/enquirer/lib/prompt.js:196:16)
    at Promise (/Users/wanghx/Workspace/larva-team/common-bin-plus/node_modules/enquirer/lib/prompt.js:212:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

And I check the code and found that you are verifying `stdin.isRaw` in `keypress.listen` ( https://github.com/enquirer/enquirer/blob/master/lib/keypress.js#L190 ) . When the code is running in `child_process` and `stdio` is `pipe`, `process.stdin` will  be instance of `net.Socket` instead of `tty.ReadStream` and it doesn't has property `isRaw`. ( 
see https://github.com/nodejs/node/blob/master/lib/internal/process/stdio.js#L58 ) , so the error was thrown.

I think it maybe need a compatibility processing?

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

no

##### Description of change

- using `stream.isTTY` instead of `stream.isRaw`.
- throw error only in situation that stream is not `process.stdin` and `tty.ReadStream`.
- check whether is tty before invoking `setRawMode` method.

### CODE REVIEW

**Comment by whxaxes** [comment]
cc @atian25

**Comment by atian25** [comment]
yes, here is some scenarios:

- use at [npm runkit](https://npm.runkit.com/enquirer)
- use at vscode debug mode
- use at a CLI which use enquirer at a fork child process

**Comment by jonschlinkert** [comment]
probably related: 

- https://github.com/enquirer/enquirer/issues/62
- https://github.com/enquirer/enquirer/issues/68

**Comment by atian25** [comment]
@jonschlinkert could you publish a patch version for this?

**Comment by jonschlinkert** [comment]
Sorry I just saw this comment. I wish I’d seen it earlier, I can still do this if necessary.

**Comment by pke** [comment]
I am still having this problem, that when using

`curl ... | myscript.js`

It will just terminate myscript with error code 0 as soon as I `await prompt`

**Comment by jonschlinkert** [comment]
> I am still having this problem, that when using

This sounds like a different issue. 

> Check out [this branch](https://github.com/pke/restlr/tree/feature/accept-piped-input) where I am reading from stdin at this line

This isn't something we have time to do. If you want to debug this yourself and create an issue with details about what the problem is, node version, OS, etc. that would be helpful.

**Pull request merged**
