### PR TITLE
feat: Add two-factor authentication using TOTP

### PR DESCRIPTION
**Pull request by rajat-sr**
Adds a new prompt example to demonstrate two-factor authentication using OTP generated by Google Authenticator.

Contains code to generate:
- Time-Based One Time Password (TOTP) using the algorithm specified in [RFC 6238](https://tools.ietf.org/html/rfc6238)
- HMAC-based One Time Password (HOTP) using the algorithm specified in [RFC 4226](https://tools.ietf.org/html/rfc4226)

The prompt example verifies Time-Based OTP generated by any Google Authenticator app using a shared secret.

A new secret can also be generated from the code.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
this is awesome! amazing work @rajat-sr!

**Comment by rajat-sr** [comment]
Thanks @jonschlinkert! :)

**Comment by rajat-sr** [comment]
Example
enquirer-2fa

**Comment by doowb** [comment]
Thanks @rajat-sr! I'll check it out and get it merged later tonight or tomorrow morning.

**Comment by chie7tain** [comment]
Fantastic Job @rajat-sr

**Pull request merged**
