### PR TITLE
feat: Add OAuth Prompt example

### PR DESCRIPTION
**Pull request by rajat-sr**

### CODE REVIEW

**Comment by rajat-sr** [comment]
enquirer-oauth

**Comment by rajat-sr** [comment]
@doowb This OAuth example is built upon AuthPrompt.
In OAuth, since all the verification is done on Github and no verification needs to be done in the prompt, in the `verify()` function I am only returning the token received from Github after successful verification.
Please let me know if we can improve this.

**Comment by rajat-sr** [comment]
Please merge this after #193 is merged.

**Comment by doowb** [comment]
@rajat-sr thanks for the PR! I've made some requests in #193 that can also be made here. I'll review and merge after the other PR.

**Comment by rajat-sr** [comment]
Made the requested changes.

**Comment by doowb** [comment]
Thanks!

**Pull request merged**
