### PR TITLE
Switches prompt-text to prompt-input.

### PR DESCRIPTION
**Pull request by skellock**
When installing `enquirer` as a dependency we get this:

```sh
warning enquirer > prompt-text@1.2.2: prompt-text has been deprecated. Use prompt-input instead
```

Looks like y'all nuked `prompt-text`:

```sh
# yarn -s info prompt-text deprecated

prompt-text has been deprecated. Use prompt-input instead
```

Apologies for the white space noise; my editor settings are a bit pushy.  I did re-run `npm run build` in the `support` dir, but it ended up deleting `TODO` and I thought that might be a bit too presumptious for this PR.

### CODE REVIEW

**Comment by skellock** [comment]
image

Tests are passing locally here.

Lemme know if I'm way off base.  I swear I haven't been drinking.

**Comment by GantMan** [comment]
Looks like a few changes to tests are needed.

Before:
https://github.com/enquirer/enquirer/blob/master/test/ask.js#L24-L27
After: 
https://github.com/enquirer/prompt-input/blob/master/test.js#L33

**Comment by skellock** [comment]
I'm not sure dude. They pass on `linux` but not `mac`.  Looking at the build history on Travis before my PR, the same failures are there too.

Maybe it's just a slow build server and hits the `2000ms` timeout period?

**Comment by GantMan** [comment]
Ahhhh yeah.   

Maybe quick test this?
```js
it('longer test', (done) => {
  // Take a siesta tests... you deserve it
}).timeout(5000);
```

**Comment by jamonholmgren** [comment]
Hey @jonschlinkert, just a friendly ping to make sure you see this. Let us know if there's anything we can do to help you out with it.

**Comment by jonschlinkert** [comment]
sorry for the delay. will review today

**Comment by jamonholmgren** [comment]
Thank you @jonschlinkert !

**Comment by jonschlinkert** [comment]
I haven't forgotten, I've been out of the office a lot this week. I'll do this ASAP. thanks!

**Comment by doowb** [comment]
@skellock thanks! I re-ran the tests and they're passing now.

**Comment by skellock** [comment]
Good stuff! Happy new year 🎉

**Pull request merged**
