### PR TITLE
Add vim direction keypresses

### PR DESCRIPTION
**Pull request by Rigellute**
Firstly, thank you for this awesome project!

My usage has left me wanting something though - vim bindings for directional movement.

As a heavy vim user, I find directional movement more convenient using tha classic `vim` bindings `hjkl` than reaching over for the arrow keys. 

Are we able to add vim bindings to `enquirer`?

I took a stab at adding these keypresses in this pull request - but is this the correct way to add support?

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Thank you!

> I took a stab at adding these keypresses in this pull request - but is this the correct way to add support?

Yes, that's correct. However, I'm pretty sure this can also be accomplished using custom actions. (@doowb correct if I'm wrong - I've been working on the next major release and I'm forgetting when this was implemented). 

There are two ways you can do this, depending on preference:



```js
const { Select } = require('enquirer');

const prompt = new Select({
  name: 'color',
  message: 'Pick a flavor',
  choices: ['apple', 'grape', 'watermelon', 'cherry', 'orange'],

  // the "keypress" method looks for user-defined functions that map to keypresses
  h() {
    return this.left();
  },
  j() {
    return this.down();
  },
  k() {
    return this.up();
  },
  l() {
    return this.right();
  }
});
```

The second approach is to pass a custom "actions" object:

```js
const { Select } = require('enquirer');

// you'll need to merge the built-in actions onto your custom actions 
// if you don't want to overwrite all of them
const actions = require('enquirer/lib/combos');
const custom = { h: 'left', j: 'down', k: 'up', l: 'right' };
actions.keys = { ...actions.keys, ...custom };

const prompt = new Select({
  name: 'color',
  message: 'Pick a flavor',
  choices: ['apple', 'grape', 'watermelon', 'cherry', 'orange'],
  // pass custom actions to prompt
  actions
});
```

**Comment by jonschlinkert** [comment]
Note that the "left" and "right" keys won't work on the select prompt in the example. But you can try those on an Input prompt after typing something in.

**Comment by sw-yx** [comment]
> the "keypress" method looks for user-defined functions that map to keypresses

man this api is so good

**Comment by Rigellute** [comment]
@jonschlinkert thank you! Impressive API indeed! 
The first approach didn't seem to work for me, but the second one did!

Thanks again 👍

**Comment by zkochan** [comment]
Seems like inquirer supports the Vim bindings by default. I noticed it when testing `yarn upgrade-interactive`.

**Comment by jonschlinkert** [comment]
> Seems like inquirer supports the Vim bindings by default

IMHO it makes little sense given that only 25% of developers use Vim: https://insights.stackoverflow.com/survey/2019#technology-_-most-popular-development-environments. That's a massive number of developers for sure, but that also means that 75% of the users of Enquirer will be confused by that behavior, including myself.

**Pull request closed without merging**
