### PR TITLE
ci: test on Linux, macOS and Windows

### PR DESCRIPTION
**Pull request by DanielRuf**
TravisCI provides Windows support now and we should see if it works in this case.

See https://blog.travis-ci.com/2018-10-11-windows-early-release

### CODE REVIEW

**Comment by g-plane** [comment]
Have you encountered any problems when it is using AppVeyor?

**Comment by DanielRuf** [comment]
At least the AppVeyor build fails. See https://ci.appveyor.com/project/enquirer/enquirer/builds/20223742

But the main goal is to use only one CI provider and TravisCI supports Windows, Linux and macOS.

**Comment by g-plane** [comment]
You have deleted the `appveyor.yml` file, so it failed.

**Comment by DanielRuf** [comment]
> You have deleted the `appveyor.yml` file, so it failed.

Ah sure, makes sense :D

**Comment by DanielRuf** [comment]
Windows builds are green so it works for us, see https://travis-ci.org/enquirer/enquirer/builds/453822337

**Comment by g-plane** [comment]
I'm not opposed to adding Windows build in Travis CI. But, AppVeyor shouldn't be disabled, because Windows build in Travis CI is in early stage while AppVeyor is stable enough.

**Comment by jonschlinkert** [comment]
> AppVeyor shouldn't be disabled, because Windows build in Travis CI is in early stage while AppVeyor is stable enough.

I'd rather remove appveyor if we can just use travis for windows. If we have issues later we can revisit and re-add appveyor.  Sound ok?

**Comment by DanielRuf** [comment]
> I'd rather remove appveyor if we can just use travis for windows. If we have issues later we can revisit and re-add appveyor. Sound ok?

That's exactly my point.

What do the others think?

**Comment by doowb** [comment]
I agree that we should just use travis-ci if it supports windows. This will make it easier to see all of the tests in one place and there will be less configuration.

**Comment by g-plane** [comment]
That's OK.

**Comment by g-plane** [comment]
After this PR merged, AppVeyor can be disabled. Also, should GitHub pages be disabled?
default

**Pull request merged**
