### PR TITLE
doc: Syntax errors in code snippets

### PR DESCRIPTION
**Pull request by adityavyas611**
Resolves:#238

- fix the code snippets in the documentation
- fix the **return** information for **NumberPrompt** & **StringPrompt**
- added snippet for **BooleanPrompt**
- added snippet for **NumberPrompt**
- added snippet for **StringPrompt**

### CODE REVIEW

**Comment by doowb** [comment]
Hi @adityavyas611, thanks for the PR!

Will you check your editor settings because it looks like there was an extra newline added between every line in the `README.md`. If you can fix that and do a force push to your fork, we'll be able to see the real changes.

Thanks.

**Comment by adityavyas611** [comment]
@doowb, I have fix the mistake. Please have a look

**Comment by adityavyas611** [comment]
@doowb , let me know if any other changes are required in this PR??

**Comment by doowb** [comment]
@adityavyas611 great thank you!

**Pull request merged**
