### PR TITLE
📦 NEW: Example MultiSelect Validate

### PR DESCRIPTION
**Pull request by ahmadawais**
Add a new example to showcase validation with the `MultiSelect` prompt.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
nice, thanks!

**Comment by ahmadawais** [comment]
Awesome! So many more to come. I'm heavily recommending this module in my https://NodeCLI.com course. I'm sure I'll be sending lots of developers to this repo.

**Comment by ahmadawais** [comment]
Hey @jonschlinkert — silly question, but doesn't the contributors' [section](https://github.com/enquirer/enquirer#contributors) auto-update?

**Comment by jonschlinkert** [comment]
Awesome! Yes, contributor are automatically added!
Thanks!!

**Comment by ahmadawais** [comment]
@jonschlinkert thanks for confirming that. For some reason, my name is not listed there even after the PR was merged. I'm wondering if there's a broken workflow here or something. Check it when you have some time. 🤔 

Thank you!

**Comment by jonschlinkert** [comment]
> For some reason, my name is not listed there even after the PR was merged

It's done pre-publish, not on merge. It would be nice to have an action for that though.

**Pull request merged**
