### PR TITLE
Upgrade ansi-colors

### PR DESCRIPTION
**Pull request by TrySound**
Enquirer uses old version. Also congrats on eslint adoption.

Here are changes in v3 -> v4

https://github.com/doowb/ansi-colors/commit/0f15d780100e07213182f856efbf0e58fe57f49c
https://github.com/doowb/ansi-colors/commit/e66ed2faab2461f3f4a7ac161a81a9b1f4b926b1

### CODE REVIEW

**Comment by TrySound** [comment]
cc @doowb @jonschlinkert

**Comment by jonschlinkert** [comment]
Thanks! 

> Also congrats on eslint adoption.

Nice! I didn't know about that.

**Comment by TrySound** [comment]
https://github.com/eslint/eslint/blob/master/package.json#L55
This saved a few megabytes in our node_modules

**Comment by jonschlinkert** [comment]
done! [published](https://www.npmjs.com/package/enquirer/v/2.3.6) and [released](https://github.com/enquirer/enquirer/releases/tag/2.3.6) as 2.3.6. Thanks again!

**Comment by TrySound** [comment]
Thanks!

**Pull request merged**
